version: "3"

services:
    jenkins:
        build: .
        container_name: jenkins
        image: jenkins/jenkins:lts
        networks:
            - jenkins_network
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - $PWD/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock

networks: 
    jenkins_network: